version: '3'
services:
  php:
    image: covidstats/php-8.2-fpm:1.0
    build:
      context: ./docker/php
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    user: 'www-data'
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_ROOT: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      COMPOSER_MEMORY_LIMIT: -1

  nginx:
    image: covidstats/nginx:1.0
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata_covidstats:/var/lib/mysql
    environment:
      MYSQL_ROOT: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
    ports:
      - "3306:3306"

volumes:
  mysqldata_covidstats:
